### PR TITLE
Run remote command after sync.

### PR DESCRIPTION
**Pull request by dsoares**
This PR adds the ability to run a remote command after syncing. It runs the configured command if `remoteExecOnUpload is true`.
See #13 and I also needed it to run a kind of "publish" script to compile my source.

NOTE: i don't know CoffeScript language. Feel free to modify the code and sorry if there's something weird in there.

### CODE REVIEW

**Comment by dingjie** [comment]
Thank for your PR. Eventually I decided to write "Trigger" to run commands in different conditions in 0.7.0. For instance, compile coffeescript to javascript only when coffeescript files modified, and also put static files to cdn or other behaviours defined in .sync-config.cson

**Comment by brunetton** [comment]
Hi all
Is this PR included in current version ? I need to use it; I tried to add `remoteExecOnUpload` and `cmds` in config but it didn't fired the command. Did I miss something ?
Thanks

**Comment by dingjie** [comment]
@brunetton Per [READme.md](https://github.com/dingjie/atom-sync/blob/master/README.md) section Trigger, add "trigger" to your config file

###### Sample ######
```
trigger:
    "*": [
        "echo \'<span class=warning>Every time you\\'ll see me</span>\'"
    ]
    "coffee": [
        "echo Compile coffeescript to js ..."
        "mkdir -p js"
        "coffee -b --output js/ --compile coffee/"
        "ls js/|xargs -I@ echo \\t@"
    ]
    "sass/style.sass": [
        "echo Compile sass to css ..."
        "mkdir -p css"
        "sass --update sass:css"
    ]
```

You can also refer to the "SSH ControlMaster" part.

**Comment by brunetton** [comment]
Thank you, I don't know how I missed it in Readme. Shame on me!

**Pull request closed without merging**
